version: '3'
services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
     - 8000:80
    volumes:
      - ./:/var/www/html

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
